# Generated by Django 5.2.6 on 2026-04-01 14:19

import figuritas.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiguritaGenerada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('imagen_final', models.ImageField(blank=True, null=True, upload_to=figuritas.models.ruta_figurita_final, verbose_name='Imagen final')),
                ('imagen_preview', models.ImageField(blank=True, null=True, upload_to=figuritas.models.ruta_figurita_preview, verbose_name='Imagen preview')),
                ('nombre_mostrado', models.CharField(blank=True, max_length=200, verbose_name='Nombre mostrado')),
                ('datos_renderizados', models.JSONField(blank=True, default=dict, verbose_name='Datos renderizados')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID de tarea Celery')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de generacion')),
            ],
            options={
                'verbose_name': 'Figurita generada',
                'verbose_name_plural': 'Figuritas generadas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaFigurita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('predeterminada', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('configuracion_visual', models.JSONField(blank=True, default=dict, verbose_name='Configuracion visual')),
                ('archivo_base', models.ImageField(blank=True, null=True, upload_to=figuritas.models.ruta_asset_plantilla, verbose_name='Archivo base')),
            ],
            options={
                'verbose_name': 'Plantilla de figurita',
                'verbose_name_plural': 'Plantillas de figurita',
                'ordering': ['nombre'],
            },
        ),
    ]
