# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figuritas', '0001_initial'),
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuritagenerada',
            name='resultado_recorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figuritas', to='imagenes.resultadorecorte', verbose_name='Resultado de recorte'),
        ),
    ]
