# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figuritas', '0002_initial'),
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuritagenerada',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figuritas', to='sesiones.sesionproceso', verbose_name='Sesion'),
        ),
        migrations.AddConstraint(
            model_name='plantillafigurita',
            constraint=models.UniqueConstraint(condition=models.Q(('predeterminada', True)), fields=('predeterminada',), name='plantilla_predeterminada_unica'),
        ),
        migrations.AddField(
            model_name='figuritagenerada',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figuritas_generadas', to='figuritas.plantillafigurita', verbose_name='Plantilla'),
        ),
    ]
