# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionProceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('token_publico', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token publico')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('trivia_completada', models.BooleanField(default=False, verbose_name='Trivia completada')),
                ('puede_subir_foto', models.BooleanField(default=False, verbose_name='Puede subir foto')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User agent')),
            ],
            options={
                'verbose_name': 'Sesion de proceso',
                'verbose_name_plural': 'Sesiones de proceso',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
