# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesiones', '0001_initial'),
        ('trivias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionproceso',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='trivias.trivia', verbose_name='Trivia'),
        ),
    ]
