# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaTrivia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto')),
                ('tipo_respuesta', models.CharField(choices=[('texto', 'Texto'), ('fecha', 'Fecha'), ('numero', 'Numero'), ('opcion_unica', 'Opcion unica'), ('select_busqueda', 'Select con busqueda')], max_length=30, verbose_name='Tipo de respuesta')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Obligatoria')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='Placeholder')),
                ('ayuda', models.TextField(blank=True, verbose_name='Ayuda')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('mapea_a_campo_sticker', models.CharField(choices=[('nombre', 'Nombre'), ('apellido', 'Apellido'), ('fecha_nacimiento', 'Fecha de nacimiento'), ('altura_cm', 'Altura en cm'), ('peso_kg', 'Peso en kg'), ('equipo', 'Equipo'), ('apodo', 'Apodo'), ('posicion', 'Posicion'), ('nacionalidad', 'Nacionalidad')], max_length=40, verbose_name='Mapea a campo del sticker')),
                ('reglas_validacion', models.JSONField(blank=True, default=dict, verbose_name='Reglas')),
            ],
            options={
                'verbose_name': 'Pregunta de trivia',
                'verbose_name_plural': 'Preguntas de trivia',
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Flujo de trivia',
                'verbose_name_plural': 'Flujos de trivia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DatosSticker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('altura_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura en cm')),
                ('peso_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso en kg')),
                ('equipo', models.CharField(blank=True, max_length=120, verbose_name='Equipo')),
                ('apodo', models.CharField(blank=True, max_length=100, verbose_name='Apodo')),
                ('posicion', models.CharField(blank=True, max_length=100, verbose_name='Posicion')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad')),
                ('equipo_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stickers_normalizados', to='catalogos.equipo', verbose_name='Equipo del catalogo')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_sticker', to='sesiones.sesionproceso', verbose_name='Sesion')),
            ],
            options={
                'verbose_name': 'Datos del sticker',
                'verbose_name_plural': 'Datos de stickers',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('etiqueta', models.CharField(max_length=120, verbose_name='Etiqueta')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='trivias.preguntatrivia', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opcion de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.AddField(
            model_name='preguntatrivia',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='trivias.trivia', verbose_name='Trivia'),
        ),
        migrations.CreateModel(
            name='RespuestaTrivia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('valor_texto', models.CharField(blank=True, max_length=255, verbose_name='Valor de texto')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor numerico')),
                ('valor_fecha', models.DateField(blank=True, null=True, verbose_name='Valor fecha')),
                ('respondida_en', models.DateTimeField(auto_now=True, verbose_name='Respondida en')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='trivias.preguntatrivia', verbose_name='Pregunta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sesiones.sesionproceso', verbose_name='Sesion')),
                ('valor_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_trivia', to='catalogos.equipo', verbose_name='Valor de equipo')),
                ('valor_opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='trivias.opcionrespuesta', verbose_name='Valor de opcion')),
            ],
            options={
                'verbose_name': 'Respuesta de trivia',
                'verbose_name_plural': 'Respuestas de trivia',
                'ordering': ['pregunta__orden', 'creado_en'],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'pregunta'), name='respuesta_unica_por_sesion_pregunta')],
            },
        ),
        migrations.AddConstraint(
            model_name='preguntatrivia',
            constraint=models.UniqueConstraint(fields=('trivia', 'codigo'), name='pregunta_trivia_codigo_unico'),
        ),
    ]
