# Generated by Django 5.2.6 on 2026-04-01 14:19

import imagenes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOriginal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('archivo', models.ImageField(upload_to=imagenes.models.ruta_foto_original, verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Mime type')),
                ('tamano_bytes', models.PositiveIntegerField(verbose_name='Tamano en bytes')),
                ('ancho', models.PositiveIntegerField(verbose_name='Ancho')),
                ('alto', models.PositiveIntegerField(verbose_name='Alto')),
                ('hash_archivo', models.CharField(db_index=True, max_length=64, verbose_name='Hash SHA256')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Foto original',
                'verbose_name_plural': 'Fotos originales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoRecorte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('proveedor_ia', models.CharField(choices=[('gemini', 'Gemini')], default='gemini', max_length=20, verbose_name='Proveedor de IA')),
                ('png_transparente', models.ImageField(blank=True, null=True, upload_to=imagenes.models.ruta_recorte, verbose_name='PNG transparente')),
                ('archivo_mascara', models.ImageField(blank=True, null=True, upload_to=imagenes.models.ruta_mascara, verbose_name='Archivo mascara')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID de tarea Celery')),
                ('modelo_gemini', models.CharField(blank=True, max_length=120, verbose_name='Modelo Gemini')),
                ('metadatos_recorte', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('errores', models.TextField(blank=True, verbose_name='Errores')),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento')),
                ('fecha_inicio_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de procesamiento')),
                ('fecha_fin_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fin de procesamiento')),
            ],
            options={
                'verbose_name': 'Resultado de recorte',
                'verbose_name_plural': 'Resultados de recorte',
                'ordering': ['-creado_en'],
            },
        ),
    ]
