# Generated by Django 5.2.6 on 2026-04-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagenes', '0001_initial'),
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotooriginal',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='sesiones.sesionproceso', verbose_name='Sesion'),
        ),
        migrations.AddField(
            model_name='resultadorecorte',
            name='foto_original',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_recorte', to='imagenes.fotooriginal', verbose_name='Foto original'),
        ),
    ]
